CREATE TABLE IF NOT EXISTS users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(256) NOT NULL UNIQUE,
	name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
	identity_id text NOT NULL UNIQUE,

	CONSTRAINT fk_users_identity_user
    FOREIGN KEY (identity_id)
    REFERENCES "AspNetUsers"("Id")
    ON DELETE restrict
);